# -*- coding: utf-8 -*-
"""karan_verb_extraction_from_chicago_web_sindhi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyFzM_xkba07IVIgomMB42FgAKqnmkbo
"""

import requests
from lxml import html
import csv
import pandas as pd
import re

url = "https://dsal.uchicago.edu/cgi-bin/app/mewaram_query.py?qs=%DA%AA%D8%B1%DA%BB&matchtype=default"

response = requests.get(url)
response.encoding = "utf-8"

tree = html.fromstring(response.text)
entries = tree.xpath('//div[@class="hw_result"]')

data = []

for entry in entries:

    headword = entry.xpath('.//a[1]/text()')
    headword = headword[0].strip() if headword else ""

    page = entry.xpath('.//a[contains(@href,"page")]/text()')
    page = page[0].replace("p.","").strip() if page else ""

    text = entry.text_content().strip()

    if "ڪرڻ" in text:

        # construction
        words = text.split()
        construction = ""
        for i in range(len(words)):
            if words[i] == "ڪرڻ" and i > 0:
                construction = words[i-1] + " ڪرڻ"

        english_parts = re.findall(r"(To [A-Za-z ,;-]+|[A-Z][a-zA-Z ,;-]+)", text)

        english_meaning = ", ".join([e.strip() for e in english_parts if len(e.strip()) > 2])

        data.append({
            "headword": headword,
            "page": page,
            "construction": construction,
            "english_meaning": english_meaning,
            "entry_text": text
        })

# Save CSV
with open("karan_with_english.csv","w",newline="",encoding="utf-8") as f:
    writer = csv.DictWriter(f,fieldnames=["headword","page","construction","english_meaning","entry_text"])
    writer.writeheader()
    writer.writerows(data)

print("Saved: karan_with_english.csv")

# Sort
df = pd.read_csv("karan_with_english.csv")
df_sorted = df.sort_values(by="headword")

df_sorted.to_csv("karan_sorted_final.csv",index=False,encoding="utf-8")

print("Saved: karan_sorted_final.csv")